Development
IBTechRaj/html-forms pull request #1
Opened 2019-02-27 14:19 UTC by IBTechRaj

2019-02-27 19:22 UTC, zlayabekrija requested changes
It was great try, but there are some changes to be made.
Please follow the instructions.
After completing, submit new review request and happy coding.

2019-02-27 19:22 UTC, zlayabekrija commented on index.html
> +	<html lang="en">
this is extra html tag please remove it

2019-02-27 19:22 UTC, zlayabekrija commented on index.html
> +				<input type="phone" id="phone-1"  name="user_phone" />
input type should be tel

2019-02-27 19:22 UTC, zlayabekrija commented on index.html
> +		<form action="">
should `action="/"`

2019-02-27 19:22 UTC, zlayabekrija commented on index.html
> +				<button type="submit" id="create-button"> Create Account </button>
the button should be centered

2019-02-27 19:22 UTC, zlayabekrija commented on style.css
> +margin-left: 40%;
these are huge margins, please find different approach.

2019-02-27 19:22 UTC, zlayabekrija commented on style.css
> +	margin-right: 140px;
this line is unnecessary if margin 0 !important is used

2019-02-27 19:22 UTC, zlayabekrija commented on style.css
> +	margin-top: 5%;
same here 5% margin is too big

2019-02-27 19:22 UTC, zlayabekrija commented on style.css
> +	padding-top: 5%;
please use px or rem or em for both padding and margin

2019-02-27 19:22 UTC, zlayabekrija commented on style.css
> +	margin: 5% 5%;
change this please

2019-02-27 19:22 UTC, zlayabekrija commented on style.css
> +	margin-left: 30%;
margin too big, please change it

2019-02-27 19:22 UTC, zlayabekrija commented on style.css
> +	margin-left: 7%;
same do pixels

2019-02-28 15:01 UTC, DanielMitiku commented
Hey Zlayabekrija, can you please see our correction.

2019-02-28 19:34 UTC, zlayabekrija approved these changes
Great work, thumbs up 👍 from me.

2019-03-01 10:18 UTC, merged